CREATE TABLE `contents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`trilha` varchar(64) NOT NULL,
	`ordem` int NOT NULL,
	`etapa` varchar(32) NOT NULL,
	`bloco` varchar(128) NOT NULL,
	`titulo` text NOT NULL,
	`publico` varchar(128),
	`formatoProducao` varchar(64),
	`portaVoz` text,
	`prioridade` varchar(16),
	`trimestre` varchar(32),
	`gancho` text,
	`topico1` text,
	`topico2` text,
	`topico3` text,
	`palavrasChave` text,
	`dadoMercado` text,
	`cta` text,
	`status` enum('A gravar','Gravado','Em edição','Aprovação','Publicado') NOT NULL DEFAULT 'A gravar',
	`gravadoPor` text,
	`gravadoPorOpenId` varchar(64),
	`dataGravacao` timestamp,
	`observacoes` text,
	`linkAprovacao` text,
	`linkVideoFinal` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `contents_id` PRIMARY KEY(`id`)
);
